
package bank.management.gui;

import bank.management.Client;
import bank.management.DBManager;
import bank.management.GUIManager;
import bank.management.LoginInfo;
import bank.management.Navigator;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

public class Splash extends JFrameBase {

    public Splash(GUIManager guiManager) {
        super(guiManager);
        initComponents();
        this.placeOnCenter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 207, 209));
        setForeground(new java.awt.Color(45, 64, 89));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 64, 89));
        jPanel1.setForeground(new java.awt.Color(45, 64, 89));

        jLabel1.setBackground(new java.awt.Color(255, 212, 96));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 212, 96));
        jLabel1.setText("EWUBL");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 212, 96));
        jLabel2.setText("East West University Bank Limited");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank/management/icons/splash.gif"))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 212, 96));
        jLabel5.setText("Developed by:");

        jLabel6.setForeground(new java.awt.Color(255, 212, 96));
        jLabel6.setText("Saif Khan (2022-2-60-063)");

        jLabel7.setForeground(new java.awt.Color(255, 212, 96));
        jLabel7.setText("Osama Bin Qashem (2022-2-60-063)");

        jLabel8.setForeground(new java.awt.Color(255, 212, 96));
        jLabel8.setText("Mahmudul Hasan Hamim (2022-2-60-063)");

        jLabel9.setForeground(new java.awt.Color(255, 212, 96));
        jLabel9.setText("Akash Shaha (2022-2-60-063)");

        jLabel10.setForeground(new java.awt.Color(255, 212, 96));
        jLabel10.setText("Shafuiqul Islam Fahim (2022-2-60-063)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addGap(0, 68, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    public JProgressBar getjProgressBar1() {
        return jProgressBar1;
    }

    @Override
    public void setAllListeners() {
        DBManager dbManager = guiManager.getDBManager();
        Navigator navigator = guiManager.getNavigator();
        ManagerHomepage managerHomepage = guiManager.getManagerHomepage();
        LoginScreen loginScreen = guiManager.getLoginScreen();
        ClientProfile clientProfile = guiManager.getClientProfile();
        
        
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                Random random = new Random();
                int progress = 0;
                while (progress < 100) {
                    try {
                        Thread.sleep(130);
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                    progress += random.nextInt(10) + 5;
                    jProgressBar1.setValue(progress);
                }
                jProgressBar1.setValue(100);

                try {
                    dbManager.loadLoginInfo();
                    dbManager.loadClientDB();
                    LoginInfo loginInfo = dbManager.getLoginInfo();
                    Date prev = loginInfo.getDate();
                    Date now = new Date();
                    long timeDiff = now.getTime() - prev.getTime();
                    if (timeDiff <= GUIManager.LOGIN_CACHE_TIME) {
                        String username = loginInfo.getUsername();
                        String password = loginInfo.getPassword();

                        if (username.equals("admin") && password.equals("admin")) {
                            guiManager.updateLoginInfo();
                            navigator.navigate(managerHomepage);
                            dispose();
                            return;
                        }

                        dbManager.loadCredentialDB();
                        HashMap<String, String> mp = dbManager.getCredentialDB();
                        if (mp.get(username).equals(password)) {
                            navigator.navigate(clientProfile);
                            dbManager.getClientDB().forEach((Client client) -> {
                                if (client.getUsername().equals(username)) {
                                    guiManager.setUserClient(client);
                                }
                            });
                            guiManager.loadClientTransactions();
                            guiManager.updateCurrentBalance();
                            dispose();
                            return;
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(GUIManager.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {

                    Logger.getLogger(GUIManager.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NullPointerException nex) {
                    // nothing
                    System.out.println("Null pointer exx");
                }

                navigator.navigate(loginScreen);
                dispose();
            }
        });
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                t.start();
            }
        });
    }
}
